print('need assistance?')
input()
print()
print('pls tell me your name')
user_name = str(input())
print()
print('hey! ' + user_name)
print('Welcome to Hecking. How can I help you :)')
print()
input()
print('please mail us your query at support@hecking.me')